org: umairjibran
app: rest-http-perf-test
service: rest-http-perf-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  rest:
    handler: handler.rest
    events:
      - http:
          method: get
          cors: true
          path: /rest
  http:
    handler: handler.http
    events:
      - httpApi:
          method: get
          path: /http
